[package]
name = "i_overlay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i_float = { path = "../i_float" }
i_shape = { path = "../i_shape" }