[package]
name = "i_overlay"
version = "0.2.2"
authors = ["Nail Sharipov <nailxsharipov@gmail.com>"]
edition = "2021"
description = "The iOverlay is a poly-bool library that supports main operations such as union, intersection, difference, xor, and self-intersection by the even-odd rule. This algorithm is based on Vatti clipping ideas but is an original implementation."
license = "MIT"
repository = "https://github.com/iShape-Rust/iOverlay"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i_float = "^0.1.0"
i_shape = "^0.1.0"