[package]
name = "i_overlay"
version = "0.11.0"
authors = ["Nail Sharipov <nailxsharipov@gmail.com>"]
edition = "2021"
description = "The iOverlay is a poly-bool library that supports main operations such as union, intersection, difference, xor, and self-intersection by the even-odd or non-zero rule. This algorithm is based on Vatti clipping ideas but is an original implementation."
license = "MIT"
repository = "https://github.com/iShape-Rust/iOverlay"


[dependencies]
i_float = { version = "^0.4.0" }
i_shape = { version = "^0.7.0" }
#i_float = { path = "../iFloat" }
#i_shape = { path = "../iShape" }


[dev-dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
rand = { version = "0.8.5", features = [] }